In [1]:
import numpy as np
import political_game as pg
# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

$$A =
\left(
\begin{array}{cc}
 u_A(A_1) & u_B(A_1) \\
 u_A(A_2) & u_B(A_2) \\
\end{array}
\right)$$

$$B =
\left(
\begin{array}{cc}
 u_B(B_1) & u_A(B_1) \\
 u_B(B_2) & u_A(B_2) \\
\end{array}
\right)$$

In [2]:
polgame = pg.PoliticalGame(num_candidates=2, social_bound=100, \
        model=pg.LinearLink, swing_voters=True, iterations=10000, \
        force_egoism=False, seed=0)
polgame.run_iterations()

Iteration   1000 POA: 1.06 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[55.00 40.00  2.00 17.00 28.00 38.00 43.39 51.72 30.11 26.47]
 [40.00 18.00  6.00  7.00 47.00 25.00 32.86 44.02 17.41 11.67]]
Iteration   2000 POA: 1.00 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[72.00  0.00 22.00 44.00 37.00 10.00 55.02 58.08 21.34 16.80]
 [ 4.00  7.00 53.00 35.00 43.00 12.00 24.96 28.57 30.50 24.64]]
Iteration   3000 POA: 1.39 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[19.00 56.00 15.00 32.00  9.00 45.00 14.20 47.60 44.48 34.16]
 [13.00 21.00 23.00 14.00 74.00  6.00 10.42 54.79 28.09 16.20]]
Iteration   4000 POA: 1.07 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[71.00 13.00  5.00  8.00 56.00 29.00 63.20 69.46 10.40  9.39]
 [17.00 42.00 17.00  6.00 68.00 18.00 39.81 46.58 22.11 21.12]]
Iteration   5000 POA: 1.34 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[52.00  4.0

In [3]:
polgame = pg.PoliticalGame(num_candidates=2, social_bound=100, \
        model=pg.Softmax, swing_voters=True, iterations=10000, \
        force_egoism=False, seed=0)
polgame.run_iterations()

Iteration   1000 POA: 1.06 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[55.00 40.00  2.00 17.00 28.00 38.00 42.44 51.36 29.30 24.98]
 [40.00 18.00  6.00  7.00 47.00 25.00 33.43 43.76 17.45 12.09]]
Iteration   2000 POA: 1.00 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[72.00  0.00 22.00 44.00 37.00 10.00 54.76 57.79 21.67 17.15]
 [ 4.00  7.00 53.00 35.00 43.00 12.00 22.71 26.02 27.98 22.81]]
Iteration   3000 POA: 1.40 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[19.00 56.00 15.00 32.00  9.00 45.00 14.10 47.05 44.24 34.58]
 [13.00 21.00 23.00 14.00 74.00  6.00 10.71 49.08 27.29 16.86]]
Iteration   4000 POA: 1.07 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[71.00 13.00  5.00  8.00 56.00 29.00 63.35 69.48 10.45  9.45]
 [17.00 42.00 17.00  6.00 68.00 18.00 38.15 44.54 23.56 22.56]]
Iteration   5000 POA: 1.34 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[52.00  4.0

In [4]:
polgame = pg.PoliticalGame(num_candidates=2, social_bound=100, \
        model=pg.BradleyTerry, swing_voters=True, iterations=10000, \
        force_egoism=False, seed=0)
polgame.run_iterations()

Iteration   1000 POA: 1.06 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[55.00 40.00  2.00 17.00 28.00 38.00 42.55 51.41 29.39 25.19]
 [40.00 18.00  6.00  7.00 47.00 25.00 33.22 43.87 17.44 11.92]]
Iteration   2000 POA: 1.00 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[72.00  0.00 22.00 44.00 37.00 10.00 54.78 57.82 21.64 17.12]
 [ 4.00  7.00 53.00 35.00 43.00 12.00 23.37 26.79 28.72 23.36]]
Iteration   3000 POA: 1.40 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[19.00 56.00 15.00 32.00  9.00 45.00 14.11 47.10 44.27 34.54]
 [13.00 21.00 23.00 14.00 74.00  6.00 10.59 50.97 27.62 16.64]]
Iteration   4000 POA: 1.07 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[71.00 13.00  5.00  8.00 56.00 29.00 63.34 69.48 10.45  9.44]
 [17.00 42.00 17.00  6.00 68.00 18.00 38.46 44.93 23.29 22.29]]
Iteration   5000 POA: 1.34 PNE position: (0, 0)
 | A (2, 3) | B (2, 3) | a (2, 2) | b (2, 2) | 
[[52.00  4.0

In [5]:
polgame = pg.PoliticalGame(num_candidates=2, social_bound=100, \
        model=pg.LinearLink, swing_voters=False, iterations=10000, \
        force_egoism=True, seed=0)
polgame.run_iterations()

Iteration   1000 POA: 1.00 PNE position: (0, 0)
 | A (2, 2) | B (2, 2) | a (2, 2) | b (2, 2) | 
[[50.00 50.00 60.00 14.00 36.68 38.78 53.70 50.34]
 [43.00 19.00 51.00 17.00 26.76 29.22 41.96 35.96]]
Iteration   2000 POA: 1.00 PNE position: (0, 1)
 | A (2, 2) | B (2, 2) | a (2, 2) | b (2, 2) | 
[[48.00 26.00 52.00 11.00 31.54 39.20 37.57 40.30]
 [39.00 28.00 52.00 32.00 25.56 34.91 39.52 42.04]]
Iteration   3000 POA: 1.00 PNE position: (0, 0)
 | A (2, 2) | B (2, 2) | a (2, 2) | b (2, 2) | 
[[40.00 55.00 82.00  7.00 24.49 27.32 67.69 56.30]
 [12.00 43.00 59.00  1.00  8.65  6.22 69.13 51.40]]
Iteration   4000 POA: 1.00 PNE position: (0, 0)
 | A (2, 2) | B (2, 2) | a (2, 2) | b (2, 2) | 
[[50.00 25.00 87.00 11.00 26.02 31.55 63.13 38.95]
 [34.00 22.00 56.00  9.00 17.67 20.38 68.15 40.53]]
Iteration   5000 POA: 1.09 PNE position: (1, 0)
 | A (2, 2) | B (2, 2) | a (2, 2) | b (2, 2) | 
[[61.00  8.00 47.00  8.00 38.21 50.40 24.77 21.78]
 [59.00 24.00 34.00 41.00 40.64 50.72 32.28 28.60]]
Itera